bookcollector/bookcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

bookcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name="about"),
    path('books/', views.books_index, name='index'),
    path('books/<int:book_id>', views.books_detail, name='detail'),
    path('books/create', views.BookCreate.as_view(), name='books_create'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='books_update'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='books_delete'),
    path('books/<int:book_id>/add_bookmark/', views.add_bookmark, name='add_bookmark'),
    path('books/<int:book_id>/assoc_reader/<int:reader_id>/', views.assoc_reader, name='assoc_reader'),
    path('books/<int:book_id>/add_photo/', views.add_photo, name='add_photo'),
    path('books/<int:book_id>/unassoc_reader/<int:reader_id>/', views.unassoc_reader, name='unassoc_reader'),
    path('readers/', views.ReaderList.as_view(), name='readers_index'),
    path('readers/<int:pk>/', views.ReaderDetail.as_view(), name='readers_detail'),
    path('readers/create/', views.ReaderCreate.as_view(), name='readers_create'),
    path('readers/<int:pk>/update/', views.ReaderUpdate.as_view(), name='readers_update'),
    path('readers/<int:pk>/delete/', views.ReaderDelete.as_view(), name='readers_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

bookcollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
class Reader(models.Model):
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('readers_detail', kwargs={'pk': self.id})


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.TextField(max_length=100)
    cost = models.IntegerField()
    readers = models.ManyToManyField(Reader)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'book_id': self.id})    


class Bookmark(models.Model):
    date = models.DateField('bookmark date')
    pagenumber = models.IntegerField()

    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return  f"{self.pagenumber} {self.date}"

    class Meta:
        ordering = ['-date']   

class Photo(models.Model):
    url = models.CharField(max_length=200)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for book_id: {self.book_id} @{self.url}"

bookcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Bookmark

class BookmarkForm(ModelForm):
  class Meta:
    model = Bookmark
    fields = ['date', 'pagenumber']

bookcollector/main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Book, Reader, Photo
from django.urls import reverse
from .forms import BookmarkForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


import logging
logging.basicConfig(level=logging.DEBUG)



    
# Create your views here.

def home(request):
    """
    home view
    http://localhostt:8000/

    """
    return render(request, 'home.html')

def about(request):
    """
    about view
    http://localhost:8000/about/

    """ 
    return render(request, 'about.html') 

@login_required
def books_index(request):
    """

    books index pages
    http://localhost:8000/books/

    """  
    logging.info('calling books_index')
    books = Book.objects.filter(user=request.user)

    return render(request, 'books/index.html', {'books' : books})

@login_required
def books_detail(request, book_id):
    """
    book details page
    http://localhost:8000/books/1  
    """     
    logging.info('calling book_details')
    book = Book.objects.get(id=book_id)
    readers_book_doesnt_have = Reader.objects.exclude(id__in = book.readers.all().values_list('id'))
    bookmark_form = BookmarkForm()
    return render(request, 'books/detail.html', {'book':book, 'bookmark_form' : bookmark_form, 'readers' : readers_book_doesnt_have})

@login_required
def add_photo(request, book_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]

        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, book_id=book_id)
        except:
            print('An error occured while uploading to s3')  
    return redirect("detail", book_id=book_id)

class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    #fields = '__all__'
    fields = ['title', 'author', 'genre', 'cost']

    def form_valid(self, form):   
        form.instance.user = self.request.user
        return super().form_valid(form)

class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    fields = ['cost']     

    success_url = "/books/"   

class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    

    success_url = "/books/"    

@login_required
def add_bookmark(request, book_id): 
    form = BookmarkForm(request.POST)
    # validate the form
    if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
        new_bookmark = form.save(commit=False)
        new_bookmark.book_id = book_id
        new_bookmark.save()
    return redirect('detail', book_id=book_id)

@login_required
def assoc_reader(request, book_id, reader_id):
  # Note that you can pass a toy's id instead of the whole toy object
    Book.objects.get(id=book_id).readers.add(reader_id)
    return redirect('detail', book_id=book_id)    

@login_required
def unassoc_reader(request, book_id, reader_id):
    Cat.objects.get(id=book_id).readers.remove(reader_id)
    return redirect('detail', book_id=book_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form' : form, 'error_message' : error_message}
    return render(request, 'registration/signup.html', context)      


class ReaderList(LoginRequiredMixin, ListView):
    model = Reader

class ReaderDetail(LoginRequiredMixin, DetailView):
    model = Reader

class ReaderCreate(LoginRequiredMixin, CreateView):
    model = Reader
    fields = '__all__'

class ReaderUpdate(LoginRequiredMixin, UpdateView):
    model = Reader
    fields = ['name']

class ReaderDelete(LoginRequiredMixin, DeleteView):
    model = Reader
    success_url = '/readers/'    

bookcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Book Collector</h1>
<hr />
<p>Hire the Book Collector!</p>

{% endblock %}

bookcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Book Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;BookCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'books_create' %}">Add a Book</a></li>
          <li><a href="{% url 'index' %}">View All My Books</a></li>
          <li><a href="{% url 'readers_create' %}">Add a Reader</a></li>
          <li><a href="{% url 'readers_index' %}">View All Readers</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Book Collector &nbsp;</div>
  </footer>
</body>
</html>

bookcollector/main_app/templates/books/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Book Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ book.title }}</span>
        <p>Author: {{ book.author }}</p>
        <p>Genre: {{ book.genre }}</p>
        <p>Cost: {{ book.cost }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'books_update' book.id %}">Edit</a>
        <a href="{% url 'books_delete' book.id %}">Delete</a>
      </div>
    </div>
    {% for photo in book.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' book.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>

  </div>
  <div class="col s6">
    <form action="{% url 'add_bookmark' book.id %}" method="post">
      {% csrf_token %}
      {{ bookmark_form.as_p }}
      <input type="submit" class="btn" value="Add Bookmark">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Page Number</th></tr>
      </thead>
      <tbody>
        {% for bookmark in book.bookmark_set.all %}
          <tr>
            <td>{{bookmark.date}}</td>
            <td>{{bookmark.pagenumber}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ book.title }}'s Readers</h3>
    {% if book.readers.count %}
      {% for reader in book.readers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ reader.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Readers :(</h5>
    {% endif %}
  </div>
  <!-- Available readers will come after this line -->
  <div class="col s6">
    <h3>Available Readers</h3>
    {% if readers.count %}
      {% for reader in readers.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ reader.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_reader' book.id reader.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{book.name}} Already Has All Readers Available</h5>
    {% endif %}
  
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

bookcollector/main_app/templates/books/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Book List</h1>



{% for book in books %}
<a href="{% url 'detail' book.id %}">
 <div class="card">
     <div class="card-content">
         <span class="card-title">{{ book.title }}</span>
         <p>Author: {{ book.author }}</p>
         <p>Genre: {{ book.genre }}</p>
         
         <p>Cost: {{ book.cost }}</p>
        
         
      
     </div>
    </a>
 </div>

{% endfor %}

{% endblock %}

bookcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

bookcollector/main_app/templates/main_app/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Book</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' book.id %}">Cancel</a>
  </form>
{% endblock %}

bookcollector/main_app/templates/main_app/book_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.title}}</span></h1>
{% else %}
<h1>Add Book</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

bookcollector/main_app/templates/main_app/reader_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Reader</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'readers_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

bookcollector/main_app/templates/main_app/reader_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Reader Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ reader.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'readers_update' reader.id %}">Edit</a>
        <a href="{% url 'readers_delete' reader.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bookcollector/main_app/templates/main_app/reader_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Reader</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

bookcollector/main_app/templates/main_app/reader_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Reader List</h1>

{% for reader in reader_list %}
  <a href="{% url 'readers_detail' reader.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ reader.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}